## 1. torch.where
#### 用法一：torch.where 筛选不等于特定值的索引

In [2]:
import torch
target = torch.tensor([3,5,7,-100,6])
ignore_index = -100
# 得到 target 中不等于 ignore_index 的索引
indices = torch.where(target != ignore_index)[0]


tensor([0, 1, 2, 4])

- 解释：torch.where(condition)[0] 用于筛选符合条件的索引，这里我们只提取符合条件的第一个维度的索引。
- 应用场景：可以用来找到特定条件下的元素位置，便于进一步操作。

#### 用法二：torch.where 根据条件更改张量的值

In [5]:
# 将 a 中不等于 3 的元素替换为 1，等于 3 的元素替换为 100
a = torch.tensor([3,3,5,7])
c = torch.where(a != 3, torch.tensor(1), torch.tensor(100))
c


tensor([100, 100,   1,   1])

- 解释：torch.where(condition, x, y) 根据条件选择值。若条件 condition 为真，则选 x，否则选 y。
- 应用场景：可以用来在同一张量中对不同条件的元素进行不同的赋值操作。

## 2. torch.gather<br>
torch.gather 截取特定索引的数据

In [3]:
# 沿着 0 维，从 target 中根据 index_target 索引获取数据
target = torch.tensor([3,5,7,-100,6])
index_target = torch.tensor([0])
result = torch.gather(target, 0, index_target)
result2 = target[index_target]
result2

tensor([3, 5])

- 解释：torch.gather(input, dim, index) 按照指定的索引 index 从 input 中提取数据。dim 指定沿哪个维度进行操作。
- 应用场景：可以用来根据索引从张量中提取特定位置的数据，适用于需要根据索引重新排列或抽取数据的场景。