## 1. 正态分布随机生成
在 PyTorch 中，可以使用 torch.normal 和 torch.randn 来生成正态分布的随机数。<br>其中 torch.normal(mean, std, size) 用于生成指定均值和标准差的正态分布，torch.randn 用于生成标准正态分布（均值为 0，标准差为 1）的随机数。

In [ ]:
import torch

# 定义 num_examples 和 w
num_examples = 5
w = [0.5, -0.2, 0.3]  # 这里假设 w 是一个长度为 3 的列表，表示 3 个特征

# 生成均值为 0，标准差为 1 的正态分布随机矩阵，形状为 (num_examples, len(w))
X = torch.normal(0, 1, (num_examples, len(w)))
print(X)

# 使用 torch.randn 生成一个 3x2 的标准正态分布随机矩阵
X = torch.randn(3, 2)
print(X)




## 2. 手写高斯分布公式
有时候，我们可以手动实现高斯分布（正态分布），公式如下：$p(x) = \frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{(x - \mu)^2}{2\sigma^2}}$


In [ ]:
import torch
import matplotlib.pyplot as plt

# 手动实现高斯分布
def gaussian_distribution(x, mu, sigma):
    # 将 sigma 转换为张量，以确保 sqrt 函数正确运行
    sigma = torch.tensor(sigma)  
    p = 1 / torch.sqrt(2 * torch.pi * sigma**2)
    return p * torch.exp(-0.5 / sigma**2 * (x - mu)**2)

# 示例：生成正态分布的随机数据并计算概率密度
mu = 0  # 均值
sigma = 1  # 标准差
x = torch.linspace(-5, 5, 100)  # 生成从-5到5的100个点
y = gaussian_distribution(x, mu, sigma)  # 计算对应的高斯分布概率密度

# 可视化结果
plt.plot(x.numpy(), y.numpy(), label=f'μ={mu}, σ={sigma}')
plt.title('Gaussian Distribution')
plt.xlabel('x')
plt.ylabel('Probability Density')
plt.legend()
plt.show()

## 3. 容易混淆的函数
在 PyTorch 中，生成随机数和随机排列有多种方法，下面是一些容易混淆的函数：

In [10]:
import torch

# 生成一个 3x3 的整数随机矩阵，值范围为 [0, 10)
x = torch.randint(0, 10, (3, 3))
print("整数随机矩阵:\n", x)

# 生成一个 3x3 的均匀分布随机矩阵，范围为 [0, 1)
x = torch.rand(3, 3)
print("均匀分布随机矩阵:\n", x)

# 生成一个 0 到 10 的随机排列
x = torch.randperm(11)
print("随机排列:\n", x)


整数随机矩阵:
 tensor([[2, 8, 5],
        [3, 7, 9],
        [9, 4, 5]])
均匀分布随机矩阵:
 tensor([[0.9035, 0.7460, 0.1593],
        [0.8438, 0.7729, 0.2883],
        [0.0739, 0.0377, 0.1250]])
随机排列:
 tensor([ 7,  5,  2,  8,  0,  1,  6,  9,  3,  4, 10])
